/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinancialServicesRegulatoryExposureRouteImport } from './routes/financial-services-regulatory-exposure'
import { Route as HealthcareComplianceBriefRouteImport } from './routes/healthcare-compliance-brief'
import { Route as PilotsRouteImport } from './routes/pilots'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as RegulatoryComplianceFrameworkRouteImport } from './routes/regulatory-compliance-framework'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialServicesRegulatoryExposureRoute =
  FinancialServicesRegulatoryExposureRouteImport.update({
    id: '/financial-services-regulatory-exposure',
    path: '/financial-services-regulatory-exposure',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthcareComplianceBriefRoute =
  HealthcareComplianceBriefRouteImport.update({
    id: '/healthcare-compliance-brief',
    path: '/healthcare-compliance-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const PilotsRoute = PilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryComplianceFrameworkRoute =
  RegulatoryComplianceFrameworkRouteImport.update({
    id: '/regulatory-compliance-framework',
    path: '/regulatory-compliance-framework',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/financial-services-regulatory-exposure': typeof FinancialServicesRegulatoryExposureRoute
  '/healthcare-compliance-brief': typeof HealthcareComplianceBriefRoute
  '/pilots': typeof PilotsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/regulatory-compliance-framework': typeof RegulatoryComplianceFrameworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/financial-services-regulatory-exposure': typeof FinancialServicesRegulatoryExposureRoute
  '/healthcare-compliance-brief': typeof HealthcareComplianceBriefRoute
  '/pilots': typeof PilotsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/regulatory-compliance-framework': typeof RegulatoryComplianceFrameworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/financial-services-regulatory-exposure': typeof FinancialServicesRegulatoryExposureRoute
  '/healthcare-compliance-brief': typeof HealthcareComplianceBriefRoute
  '/pilots': typeof PilotsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/regulatory-compliance-framework': typeof RegulatoryComplianceFrameworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/financial-services-regulatory-exposure'
    | '/healthcare-compliance-brief'
    | '/pilots'
    | '/pricing'
    | '/product'
    | '/regulatory-compliance-framework'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/financial-services-regulatory-exposure'
    | '/healthcare-compliance-brief'
    | '/pilots'
    | '/pricing'
    | '/product'
    | '/regulatory-compliance-framework'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/financial-services-regulatory-exposure'
    | '/healthcare-compliance-brief'
    | '/pilots'
    | '/pricing'
    | '/product'
    | '/regulatory-compliance-framework'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  FinancialServicesRegulatoryExposureRoute: typeof FinancialServicesRegulatoryExposureRoute
  HealthcareComplianceBriefRoute: typeof HealthcareComplianceBriefRoute
  PilotsRoute: typeof PilotsRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  RegulatoryComplianceFrameworkRoute: typeof RegulatoryComplianceFrameworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-services-regulatory-exposure': {
      id: '/financial-services-regulatory-exposure'
      path: '/financial-services-regulatory-exposure'
      fullPath: '/financial-services-regulatory-exposure'
      preLoaderRoute: typeof FinancialServicesRegulatoryExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare-compliance-brief': {
      id: '/healthcare-compliance-brief'
      path: '/healthcare-compliance-brief'
      fullPath: '/healthcare-compliance-brief'
      preLoaderRoute: typeof HealthcareComplianceBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots': {
      id: '/pilots'
      path: '/pilots'
      fullPath: '/pilots'
      preLoaderRoute: typeof PilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-compliance-framework': {
      id: '/regulatory-compliance-framework'
      path: '/regulatory-compliance-framework'
      fullPath: '/regulatory-compliance-framework'
      preLoaderRoute: typeof RegulatoryComplianceFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  FinancialServicesRegulatoryExposureRoute:
    FinancialServicesRegulatoryExposureRoute,
  HealthcareComplianceBriefRoute: HealthcareComplianceBriefRoute,
  PilotsRoute: PilotsRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  RegulatoryComplianceFrameworkRoute: RegulatoryComplianceFrameworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
